name: Run Python Tests

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Also trigger on pull requests targeting the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your project's Python version

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 'latest'
          virtualenvs-create: true # Create a virtual environment for dependencies
          virtualenvs-in-project: true # Keep venv in project for caching (optional)

      - name: Install dependencies
        run: poetry install --no-interaction --no-root # Install dependencies, not the package itself as editable

      - name: Run tests
        run: poetry run pytest # Or your specific test command, e.g., poetry run python -m unittest discover
        # If you have specific pytest options, add them here, e.g., poetry run pytest -v